all:
  children:
    linux_nodes:
      children:
        vsphere_vms:
    vsphere_vms:
      hosts:
        nawex-onprem-node-01:
          ansible_host: 192.168.50.10
        nawex-onprem-node-02:
          ansible_host: 192.168.50.11
        nawex-onprem-node-03:
          ansible_host: 192.168.50.12
        nawex-onprem-node-04:
          ansible_host: 192.168.50.13
      vars:
        ansible_user: ubuntu
        ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
