apiVersion: v1
kind: Namespace
metadata:
  name: nawex-migrated
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    nawex.io/target-cluster: aws-eks
