global:
  scrape_interval: 15s

rule_files:
  - ../alerts/slo-alerts.yml

scrape_configs:
  - job_name: nawex-api
    static_configs:
      - targets: ["nawex-api.nawex-platform.svc.cluster.local:80"]
