apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nawex-dev
  namespace: argocd
spec:
  project: nawex-platform
  source:
    repoURL: https://github.com/example-org/nawex-hybrid-devops-platform.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: nawex-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
