apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nawex-platform
  namespace: argocd
spec:
  description: NAWEX hybrid platform GitOps project
  sourceRepos:
    - https://github.com/Here2ServeU/nawex-hybrid-devops-platform.git
  destinations:
    - namespace: nawex-dev
      server: https://kubernetes.default.svc
    - namespace: nawex-onprem
      server: https://kubernetes.default.svc
    - namespace: nawex-staging
      server: https://kubernetes.default.svc
    - namespace: nawex-prod
      server: https://kubernetes.default.svc
    - namespace: nawex-local
      server: https://kubernetes.default.svc
    - namespace: nawex-migrated
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: ConfigMap
    - group: apps
      kind: Deployment
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: route.openshift.io
      kind: Route
  orphanedResources:
    warn: true
  roles:
    - name: read-only
      description: Read-only visibility into nawex-platform apps
      policies:
        - p, proj:nawex-platform:read-only, applications, get, nawex-platform/*, allow
    - name: ops
      description: Operators who can sync but not delete
      policies:
        - p, proj:nawex-platform:ops, applications, get, nawex-platform/*, allow
        - p, proj:nawex-platform:ops, applications, sync, nawex-platform/*, allow
        - p, proj:nawex-platform:ops, applications, action/*, nawex-platform/*, allow
