name: terraform

on:
  pull_request:
    paths:
      - "infra/terraform/**"
      - ".github/workflows/terraform.yml"
  workflow_dispatch:

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      - run: terraform fmt -check -recursive infra/terraform

  validate:
    name: validate + plan (${{ matrix.env }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [dev, staging, prod, onprem, aws-eks, azure-aks, openshift-rosa, openshift-vsphere]
    defaults:
      run:
        working-directory: infra/terraform/envs/${{ matrix.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      - run: terraform init -backend=false
      - run: terraform validate
      - name: Terraform plan (skipped for cloud envs without creds)
        if: matrix.env != 'aws-eks' && matrix.env != 'azure-aks' && matrix.env != 'onprem' && matrix.env != 'openshift-rosa' && matrix.env != 'openshift-vsphere'
        run: terraform plan -lock=false -input=false

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: infra/terraform
          soft_fail: false

  checkov:
    name: checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/terraform
          framework: terraform
          quiet: true
          soft_fail: false
